name: Release Update

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Workflows
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Timestamp
        id: time
        uses: 1466587594/get-current-time@v2
        with:
          format: MMM. D, YYYY # Pulls the tag name and current date to produce clientVersion -> v1.0.0, Jan. 1, 1970

      - name: Build Client
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV # The name of the tag which triggered the build

          echo "CHANGELOG<<EOF" >> $GITHUB_ENV # These 3 lines are very confusing but github is weird so they are needed, gets the last entry into the changelog.
          awk -v RS='#' 'NR==3{printf"#### "; print; printf"\n"; exit}' core/assets/changelog >> $GITHUB_ENV
          echo EOF >> $GITHUB_ENV

          ./gradlew test desktop:dist -PupdateUrl=${{ github.repository }} -PclientVersion="${GITHUB_REF/refs\/tags\//}, ${{ steps.time.outputs.formattedTime }}" --parallel # Testing and building in parallel saves a few dozen seconds.

      - name: Upload Test Results To Pages
        if: ${{ !cancelled() }}
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: tests/build/reports/tests/test
          silent: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.VERSION }} (${{ steps.time.outputs.formattedTime }})
          body: | # The release body with the latest set of changes from the changelog
            # Foo's Client (${{ env.VERSION }})
            ### Steam installation instructions [here](../../#steam)
            ## Latest Changelog (May be out of date)
            ${{ env.CHANGELOG }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: desktop/build/libs/Mindustry.jar
          asset_name: desktop.jar
          asset_content_type: application/zip

      - name: Upload Artifact # Only uploaded on fail to save some time
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Zipped Jar
          path: desktop/build/libs/Mindustry.jar
